Repository nujovich/kurojam-sparta, pull requests merged in 2023-08, with the labels that each got.

#2 feat: turborepo + vite
  .eslintrc.js
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .npmrc
  README.md
  apps/client/.eslintrc.cjs
  apps/client/.gitignore
  apps/client/README.md
  apps/client/index.html
  apps/client/package.json
  apps/client/public/vite.svg
  apps/client/src/App.css
  apps/client/src/App.jsx
  apps/client/src/assets/react.svg
  apps/client/src/index.css
  apps/client/src/main.jsx
  apps/client/vite.config.js
  apps/server/.gitkeep
  package.json
  packages/.gitkeep
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo.json
Labels: chore

#3 fix: dependencies
  package.json
  pnpm-lock.yaml
Labels: bug, chore

#4 feat: adding shadcn to client
  apps/client/components.json
  apps/client/package.json
  apps/client/postcss.config.js
  apps/client/src/App.css
  apps/client/src/App.jsx
  apps/client/src/components/ButtonDemo.jsx
  apps/client/src/components/theme-provider.jsx
  apps/client/src/components/ui/button.jsx
  apps/client/src/index.css
  apps/client/src/lib/utils.tsx
  apps/client/src/main.jsx
  apps/client/src/styles/globals.css
  apps/client/src/vite-env.d.ts
  apps/client/tailwind.config.cjs
  apps/client/tsconfig.json
  apps/client/tsconfig.node.json
  apps/client/vite.config.js
  pnpm-lock.yaml
Labels: enhancement

#8 feat: adding node volta package manager
  apps/client/package.json
  apps/server/package.json
  package.json
  pnpm-lock.yaml
Labels: chore

#11 feat: adding routes, controllers, utils and mongo connection
  apps/server/.env.template
  apps/server/controllers/memes.js
  apps/server/express.js
  apps/server/index.js
  apps/server/models/Memes.js
  apps/server/package.json
  apps/server/routes/index.js
  apps/server/routes/memes.js
  apps/server/utils/db.js
  pnpm-lock.yaml
Labels: backend, chore

#17 feat: adding clerk for login users
  apps/client/.env.template
  apps/client/package.json
  apps/client/src/App.jsx
  apps/client/src/main.jsx
  pnpm-lock.yaml
Labels: frontend, chore

#20 feat: dashboard improvements - Routers - Navigation - Avatar - Dark Mode Button
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/src/App.jsx
  apps/client/src/components/Layout.jsx
  apps/client/src/components/main-nav.jsx
  apps/client/src/components/mode-toggle.jsx
  apps/client/src/components/ui/avatar.jsx
  apps/client/src/components/ui/dropdown-menu.jsx
  apps/client/src/components/user-nav.jsx
  apps/client/src/main.jsx
  apps/client/src/pages/home.jsx
  pnpm-lock.yaml
Labels: enhancement, frontend

#22 issue nvmrc hotfix
  .nvmrc
Labels: bug

#24 fix: bad merge clerk
  apps/client/src/main.jsx
Labels: bug, frontend

#26 feat: adding trending images in home
  apps/client/index.html
  apps/client/package.json
  apps/client/src/components/Layout.jsx
  apps/client/src/pages/home.jsx
  apps/server/controllers/memes.js
  apps/server/models/Memes.js
  apps/server/routes/memes.js
  pnpm-lock.yaml
Labels: backend, frontend

#31 feat: rate page
  apps/client/index.html
  apps/client/public/duck.svg
  apps/client/src/App.jsx
  apps/client/src/components/Layout.jsx
  apps/client/src/components/main-nav.jsx
  apps/client/src/components/serachbar/SearchBar.jsx
  apps/client/src/components/ui/skeleton.jsx
  apps/client/src/pages/rate.jsx
  apps/server/.env.template
  apps/server/controllers/memes.js
  apps/server/index.js
  apps/server/package.json
  apps/server/routes/memes.js
  apps/server/services/ai.js
  apps/server/services/clerk.js
  pnpm-lock.yaml
Labels: backend, frontend

#21 Feat/prettier eslint config
  apps/client/.eslintrc.cjs
  apps/client/.prettierrc
  apps/client/index.html
  apps/client/package.json
  apps/client/src/App.jsx
  apps/client/src/components/ButtonDemo.jsx
  apps/client/src/components/cloudinary/ImageDataFunction.jsx
  apps/client/src/components/cloudinary/UploadWidget.jsx
  apps/client/src/components/theme-provider.jsx
  apps/client/src/components/ui/button.jsx
  apps/client/src/lib/constants.js
  apps/client/src/lib/entity.js
  apps/client/src/lib/fetchCreator.js
  apps/client/src/lib/utils.js
  apps/client/src/main.jsx
  apps/client/src/styles/globals.css
  apps/client/tailwind.config.ts
  apps/client/vite.config.ts
Labels: enhancement

#35 Click logo and go to home
  apps/client/src/components/main-nav.jsx
Labels: enhancement, frontend

#37 feat: adding api url for render
  apps/client/.env.template
  apps/client/src/lib/constants.js
Labels: frontend

#40 fix: better handling error
  apps/client/src/App.jsx
  apps/client/src/pages/error.jsx
  apps/client/src/pages/home.jsx
  apps/client/src/pages/rate.jsx
  pnpm-lock.yaml
Labels: bug, frontend

#39 feat: search ducks on frontend
  apps/client/src/components/serachbar/SearchBar.jsx
  apps/client/src/pages/home.jsx
Labels: frontend

#41 Feat/about page
  apps/client/src/App.jsx
  apps/client/src/components/main-nav.jsx
  apps/client/src/pages/about.jsx
Labels: enhancement, frontend

#42 mobile-view styles
  apps/client/src/components/cloudinary/UploadWidget.jsx
  apps/client/src/components/main-nav.jsx
Labels: enhancement, frontend
